EXECUTE BLOCK AS
BEGIN
  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$FIELDS f
      WHERE TRIM(f.RDB$FIELD_NAME) = 'DM_AMOUNT'
  )) THEN
    EXECUTE STATEMENT 'CREATE DOMAIN DM_AMOUNT AS DECIMAL(18,2)';

  IF (NOT EXISTS(
      SELECT 1
      FROM RDB$FIELDS f
      WHERE TRIM(f.RDB$FIELD_NAME) = 'DM_NAME'
  )) THEN
    EXECUTE STATEMENT 'CREATE DOMAIN DM_NAME AS VARCHAR(1000)';
END;
