EXECUTE BLOCK AS
BEGIN
  -- Create table if missing
  IF (NOT EXISTS(
      SELECT 1 FROM RDB$RELATIONS r
      WHERE r.RDB$RELATION_NAME = 'PRODUCTS'
        AND COALESCE(r.RDB$SYSTEM_FLAG, 0) = 0
  )) THEN
    EXECUTE STATEMENT 'CREATE TABLE PRODUCTS (ID INTEGER)';

  -- Add column NAME if missing
  IF (NOT EXISTS(
      SELECT 1 FROM RDB$RELATION_FIELDS rf
      WHERE rf.RDB$RELATION_NAME = 'PRODUCTS'
        AND rf.RDB$FIELD_NAME = 'NAME'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE PRODUCTS ADD NAME DM_NAME';

  -- Add column PRICE if missing
  IF (NOT EXISTS(
      SELECT 1 FROM RDB$RELATION_FIELDS rf
      WHERE rf.RDB$RELATION_NAME = 'PRODUCTS'
        AND rf.RDB$FIELD_NAME = 'PRICE'
  )) THEN
    EXECUTE STATEMENT 'ALTER TABLE PRODUCTS ADD PRICE DM_AMOUNT';
END

